MUN_AML = ('CASCAIS', 'LISBOA', 'LOURES', 'MAFRA', 'OEIRAS', 'SINTRA', 'VILA FRANCA DE XIRA',
           'AMADORA', 'ODIVELAS', 'ALCOCHETE', 'ALMADA', 'BARREIRO', 'MOITA', 'MONTIJO', 'PALMELA',
           'SEIXAL', 'SESIMBRA', 'SETÚBAL')

DB_PATH = '../db.sqlite'
